# Generated by Django 4.2.23 on 2025-09-07 15:42

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        # No operations needed — skipping broken rename
    ]
