# Generated by Django 4.2.23 on 2025-09-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
