# Generated by Django 4.2.23 on 2025-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_message_options_message_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(default='(No Subject)', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('archived', 'Archived')], default='inbox', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='subject_override',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
