# Generated by Django 4.2.23 on 2025-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_message_options_conversation_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox')], default='inbox', max_length=20),
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
