# Generated by Django 4.2.23 on 2025-09-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_forumcategory_forumpost_forumpostcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='forum_documents/'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
        migrations.DeleteModel(
            name='ForumPostCommentLike',
        ),
    ]
