# Generated by Django 4.2.23 on 2025-09-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_forumpost_document_forumpost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpostcommentreport',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='forumpostcommentreport',
            name='reported_by',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='is_reported',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='views',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('edu', 'Education'), ('art', 'Art & Creativity'), ('science', 'Science'), ('business', 'Business & Entrepreneurship'), ('health', 'Health & Wellness'), ('gaming', 'Gaming'), ('social', 'Social Impact'), ('entertainment', 'Entertainment'), ('sports', 'Sports & Fitness'), ('travel', 'Travel & Lifestyle'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='ForumCategory',
        ),
        migrations.DeleteModel(
            name='ForumPostCommentReport',
        ),
    ]
