# Generated by Django 4.2.23 on 2025-09-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_remove_forumpostcommentreport_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('edu', 'Education'), ('art', 'Art & Creativity'), ('science', 'Science'), ('business', 'Business & Entrepreneurship'), ('health', 'Health & Wellness'), ('gaming', 'Gaming'), ('social', 'Social Impact'), ('entertainment', 'Entertainment'), ('sports', 'Sports & Fitness'), ('travel', 'Travel & Lifestyle'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
