# Generated by Django 4.2.23 on 2025-09-08 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_remove_forumpost_created_at_alter_forumpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
