# Generated by Django 4.2.23 on 2025-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_forumpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
