# Generated by Django 4.2.23 on 2025-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_forumpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'verbose_name': 'Forum Post', 'verbose_name_plural': 'Forum Posts'},
        ),
        migrations.AddField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('edu', 'Education'), ('art', 'Art & Creativity'), ('science', 'Science'), ('business', 'Business & Entrepreneurship'), ('health', 'Health & Wellness'), ('gaming', 'Gaming'), ('social', 'Social Impact'), ('entertainment', 'Entertainment'), ('sports', 'Sports & Fitness'), ('travel', 'Travel & Lifestyle'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
