# Generated by Django 4.2.23 on 2025-09-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_alter_forumpost_options_forumpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Forum Post', 'verbose_name_plural': 'Forum Posts'},
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['slug'], name='ideas_forum_slug_a814f8_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['category'], name='ideas_forum_categor_22da0f_idx'),
        ),
    ]
